### ISSUE TITLE
Transcriptions

### ISSUE THREAD

**Issue by aldahick** [aldahick/rex#1]
See `# /mzk` in the [README](https://github.com/aldahick/rex) for background.

Registered users should be able to upload size-limited recordings, and some time (5 minutes, usually, maybe) after starting a transcription. they can download sheet music which approximately represents their recording.

## Unsolved problems

not actually unsolved, I just haven't looked at these hard enough yet

- [ ] Convert Omnizart's MIDI output to PDF
- [ ] Google Cloud costs versus local server performance
- [ ] Audio file conversion (for Omnizart input)

## Todo

- [ ] Implement frontend
  - [ ] View media as file browser
  - [ ] Manage media in file browser
  - [ ] View transcription jobs
  - [ ] Start transcriptions
- [ ] Make sure I don't go broke
  - [ ] Implement global concurrent job limit
  - [ ] Implement per-role upload and download limit
- [ ] Remove/lower the limits as/if traffic increases
  - [ ] Implement improved monitoring of jobs and user abuse
  - [ ] Implement garbage detection (mostly throw out invalid "recordings" before container start)
